name: dunkingclub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.2
  equatable: ^2.0.7
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter 
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images_avatar/
   - assets/images_courts/
   - assets/icons/
   - assets/icons_chat/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon_icon_nba.png 
   

flutter_native_splash:
  color: "#2E2E2E"
  image: assets/splach/icon_splash.png
  