// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5uu_vphb4iVc-S2q-94ST_-MegFwICE',
    appId: '1:177075689389:web:e854a96f85902939a93324',
    messagingSenderId: '177075689389',
    projectId: 'dunkingclub',
    authDomain: 'dunkingclub.firebaseapp.com',
    storageBucket: 'dunkingclub.firebasestorage.app',
    measurementId: 'G-Q7HFZRJHM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ePQ-qf_01RKU094-UCr9BNMxh8MVz0c',
    appId: '1:177075689389:android:d6fe7796c219790ea93324',
    messagingSenderId: '177075689389',
    projectId: 'dunkingclub',
    storageBucket: 'dunkingclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGH_1W6Nf5l9jlAlUdSOPPx9auOwWrTZ4',
    appId: '1:177075689389:ios:e4fae5863dc15800a93324',
    messagingSenderId: '177075689389',
    projectId: 'dunkingclub',
    storageBucket: 'dunkingclub.firebasestorage.app',
    iosBundleId: 'com.example.dunkingclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGH_1W6Nf5l9jlAlUdSOPPx9auOwWrTZ4',
    appId: '1:177075689389:ios:e4fae5863dc15800a93324',
    messagingSenderId: '177075689389',
    projectId: 'dunkingclub',
    storageBucket: 'dunkingclub.firebasestorage.app',
    iosBundleId: 'com.example.dunkingclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5uu_vphb4iVc-S2q-94ST_-MegFwICE',
    appId: '1:177075689389:web:f77d71c95b926d8ca93324',
    messagingSenderId: '177075689389',
    projectId: 'dunkingclub',
    authDomain: 'dunkingclub.firebaseapp.com',
    storageBucket: 'dunkingclub.firebasestorage.app',
    measurementId: 'G-FH65HB9SQ1',
  );
}