import 'package:dunkingclub/feature/players/models/player.dart';

List<Player> players = [
  Player(
    userId: "",
    firstName: "Michael",
    lastName: "Jordan",
    nickName: "MJ",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    eMail: "mj@mail.mail",
    password: "mj123",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Mike",
    lastName: "Viking",
    nickName: "MV",
    eMail: "mv@mail.mail",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "mv123",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Shaquille",
    lastName: "O'Neal",
    nickName: "Shaq",
    eMail: "sh@mail.mail",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "sq",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Dražen ",
    lastName: "Petrović",
    nickName: "Basketball-Mozart",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Stephen",
    lastName: "Curry",
    nickName: "Chef Curry",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Toni",
    lastName: "Kukoč ",
    nickName: "Die kroatische Sensation",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Dino",
    lastName: "Rađa",
    nickName: "König von Split",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Kevin",
    lastName: "Durant",
    nickName: "KD",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    nickName: "Greek Freak",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "assets/images/antetokounmpo.png",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "James",
    lastName: "Harden",
    nickName: "The Beard",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Dirk",
    lastName: "Nowitzki",
    nickName: "Wunderkind",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Nein'],
    sendMessage: false,
    online: true,
  ),
  Player(
    userId: "",
    firstName: "Tim",
    lastName: "Duncan",
    nickName: "The Big Fundamental",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Vielleicht'],
    sendMessage: false,
    online: false,
  ),
  Player(
    userId: "",
    firstName: "Magic",
    lastName: "Johnson",
    nickName: "Magic",
    eMail: "",
    continent: "EU",
    country: "Germany",
    cityCode: "87600",
    password: "",
    avatarUrl: "",
    availability: ['Ja'],
    sendMessage: false,
    online: true,
  ),
];
